from pathlib import Path
import re

p = Path("benchmarks/candidate_promotion/experiments/rgv_pilot/run_suite.py")
s = p.read_text(encoding="utf-8")

start = s.index("def load_tap_features(")
end = s.index("\n\ndef clean_mask(", start)

replacement = 'def load_tap_features(path: Path, cohort: pd.DataFrame) -> np.ndarray:\n    tap = pd.read_csv(path)\n    id_candidates = [\n        c for c in tap.columns\n        if str(c).strip().lower() in {"antibody_id", "id", "antibody", "name", "antibody_name"}\n    ]\n    id_col = id_candidates[0] if id_candidates else tap.columns[0]\n\n    id_key = str(id_col).strip().lower()\n    if id_key == "antibody_name":\n        cohort_key = "antibody_name"\n    elif id_key in {"antibody_id", "id", "antibody"}:\n        cohort_key = "antibody_id"\n    elif id_key == "name" and "antibody_name" in cohort.columns:\n        cohort_key = "antibody_name"\n    else:\n        raise ValueError(f"unsupported TAP identity column:{id_col}")\n\n    if cohort_key not in cohort.columns:\n        raise ValueError(f"cohort missing TAP identity key:{cohort_key}")\n\n    feat = tap.copy()\n    feat["_join"] = feat[id_col].astype(str).str.strip().str.casefold()\n    ref = cohort[[cohort_key]].copy()\n    ref["_join"] = ref[cohort_key].astype(str).str.strip().str.casefold()\n\n    if feat["_join"].duplicated().any():\n        raise ValueError("duplicate TAP identity after normalization")\n    if ref["_join"].duplicated().any():\n        raise ValueError("duplicate cohort identity after normalization")\n\n    merged = ref.merge(feat, on="_join", how="left", validate="one_to_one", indicator=True)\n    missing = merged["_merge"] != "both"\n    if missing.any():\n        examples = ref.loc[missing, cohort_key].astype(str).head(5).tolist()\n        raise ValueError(\n            f"TAP identity coverage incomplete:{int(missing.sum())}/{len(ref)} missing; examples={examples}"\n        )\n\n    excluded = {\n        id_col, "_join", "_merge", cohort_key,\n        "antibody_id", "antibody_id_x", "antibody_id_y",\n        "antibody_name", "antibody_name_x", "antibody_name_y",\n    }\n    numeric = {}\n    for c in merged.columns:\n        if c in excluded:\n            continue\n        vals = pd.to_numeric(merged[c], errors="coerce")\n        if vals.notna().any():\n            numeric[c] = vals\n    if not numeric:\n        raise ValueError("no numeric TAP features after identity join")\n    frame = pd.DataFrame(numeric)\n    if frame.isna().all(axis=1).any():\n        raise ValueError("at least one cohort antibody has no numeric TAP features")\n    frame = frame.fillna(frame.median(numeric_only=True)).fillna(0.0)\n    return frame.to_numpy(float)\n'

p.write_text(s[:start] + replacement + s[end:], encoding="utf-8")
print(f"patched {p}")
